// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRP7E4fdhEDGzL3LWtkJE2tCQvIFfCKkE',
    appId: '1:416410080708:web:547474f28b16190f990091',
    messagingSenderId: '416410080708',
    projectId: 'kemet-odyssey',
    authDomain: 'kemet-odyssey.firebaseapp.com',
    storageBucket: 'kemet-odyssey.firebasestorage.app',
    measurementId: 'G-LC60KL1X04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2T1G3IYUdlZQW0Iq5cduqJumr-BDlOYI',
    appId: '1:416410080708:android:5fc61389bd86675c990091',
    messagingSenderId: '416410080708',
    projectId: 'kemet-odyssey',
    storageBucket: 'kemet-odyssey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD_bAz6zxtgPGvB_Hm65AsgZ32pyK03Nw',
    appId: '1:416410080708:ios:a25d3cd5df8f2131990091',
    messagingSenderId: '416410080708',
    projectId: 'kemet-odyssey',
    storageBucket: 'kemet-odyssey.firebasestorage.app',
    iosBundleId: 'com.example.kemetOdyssey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD_bAz6zxtgPGvB_Hm65AsgZ32pyK03Nw',
    appId: '1:416410080708:ios:a25d3cd5df8f2131990091',
    messagingSenderId: '416410080708',
    projectId: 'kemet-odyssey',
    storageBucket: 'kemet-odyssey.firebasestorage.app',
    iosBundleId: 'com.example.kemetOdyssey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRP7E4fdhEDGzL3LWtkJE2tCQvIFfCKkE',
    appId: '1:416410080708:web:cf8ea46e88966932990091',
    messagingSenderId: '416410080708',
    projectId: 'kemet-odyssey',
    authDomain: 'kemet-odyssey.firebaseapp.com',
    storageBucket: 'kemet-odyssey.firebasestorage.app',
    measurementId: 'G-QGYBX1XRBX',
  );
}
